#!/bin/bash

# switch to environment JVM as needed
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
# JAVA_HOME=/usr

SCRIPT_DIR=/home/symflower

SYM=$SCRIPT_DIR/lib/symflower
TOOL=$SCRIPT_DIR/lib/symflower_runtool-1.0.0.jar


java -cp $SCRIPT_DIR:$SYM:$TOOL sbst.runtool.Main
