#!/bin/bash

# switch to environment JVM as needed
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
# JAVA_HOME=/usr

SCRIPT_DIR=/home/tackletest

TACK=$SCRIPT_DIR/lib/tackletest
TOOL=$SCRIPT_DIR/lib/tackletest_runtool-1.0.0.jar


java -cp $SCRIPT_DIR:$TACK:$TOOL sbst.runtool.Main
