#!/bin/bash

# Set the script's directory
SCRIPT_DIR=/home/evosuite

# Define the paths to EvoSuite and the runtool JAR
EVO=$SCRIPT_DIR/lib/evosuite.jar
TOOL=$SCRIPT_DIR/lib/evosuite_runtool-1.0.0.jar

# Set the classpath
CLASSPATH=$SCRIPT_DIR:$EVO:$TOOL

# Run EvoSuite using the classpath
java -cp "$CLASSPATH" sbst.runtool.Main
